kind: Secret
apiVersion: v1
metadata:
  name: aiw-secret
data:
  dbhost: {{ .Values.secret.dbhost | b64enc  }}
  dbuser: {{ .Values.secret.dbuser | b64enc  }}
  dbpassword: {{ .Values.secret.dbpassword | b64enc  }}
  aws_access_key_id: {{ .Values.secret.aws_access_key_id | b64enc  }}
  aws_secret_access_key: {{ .Values.secret.aws_secret_access_key | b64enc  }}
  mlflow_s3_endpoint_url: {{ .Values.secret.mlflow_s3_endpoint_url | b64enc  }} 
type: Opaque