apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aiw-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec: 
  rules:
  - http:
      paths:
      {{- if .Values.global.dashboard.enabled }}
      - path: /home
        backend:
          serviceName: ai-workspace-dashboard
          servicePort: 80
      {{- end }}
      {{- if .Values.global.theia.enabled }}
      - path: /ide
        backend:
          serviceName: ai-workspace-theia
          servicePort: 3000
      {{- end }}
      {{- if .Values.global.jupyterhub.enabled }}
      - path: /hub
        backend:
          serviceName: hub
          servicePort: 8081
      {{- end }}
      {{- if .Values.global.minio.enabled }}
      - path: /minio
        backend:
          serviceName: ai-workspace-minio
          servicePort: 9000
      {{- end }}
      {{- if .Values.global.airflow.enabled }}
      - path: /airflow
        backend:
          serviceName: ai-workspace-airflow-web
          servicePort: 8080
      {{- end }}
      {{- if .Values.global.mlflow.enabled }}
      - path: /mlflow
        backend:
          serviceName: ai-workspace-mlflow
          servicePort: 5000
      {{- end }}
      {{- if .Values.global.phpmyadmin.enabled }}
      - path: /db
        backend:
          serviceName: ai-workspace-phpmyadmin
          servicePort: 80
      {{- end }}
      {{- if .Values.global.tensorboard.enabled }}
      - path: /tensorboard
        backend:
          serviceName: ai-workspace-tensorboard
          servicePort: 6006
      {{- end }}