apiVersion: v2
name: helm-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: dashboard
    version: 0.1.0
    condition: global.dashboard.enabled
  - name: mlflow
    version: 0.1.0
    condition: global.mlflow.enabled
  - name: theia
    version: 0.1.0
    condition: global.theia.enabled
  - name: phpmyadmin
    version: 0.1.0
    condition: global.phpmyadmin.enabled
  - name: jupyterhub
    version: 0.9.0
    repository: "@jupyterhub"
    condition: global.jupyterhub.enabled
    alias: jupyterhub
  - name: mysql
    version: 1.4.0
    repository: "@stable"
    condition: global.mysql.enabled
    alias: mysql
  - name: minio
    version: 5.0.26
    repository: "@stable"
    condition: global.minio.enabled
    alias: minio
  - name: airflow
    version: 7.1.3
    repository: "@stable"
    condition: global.airflow.enabled
    alias: airflow