apiVersion: v2
name: helm-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: dashboard
    condition: dashboard.enabled
  - name: mlflow
    condition: mlflow.enabled
  - name: phpmyadmin
    condition: phpmyadmin.enabled
  - name: mysql
    version: 1.4.0
    repository: "@stable"
    condition: mysql.enabled
    alias: mysql
  - name: minio
    version: 5.0.26
    repository: "@stable"
    condition: minio.enabled
    alias: minio
  - name: airflow
    version: 7.1.3
    repository: "@stable"
    condition: airflow.enabled
    alias: airflow