# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
    secret:
        dbhost: ai-workspace-mysql
        dbuser: root
        dbpassword: PASSWORD
        aws_access_key_id: minio
        aws_secret_access_key: minio123
        mlflow_s3_endpoint_url: http://ai-workspace-minio:9000 

dashboard:
    enabled: true

mlflow:
    enabled: true

phpmyadmin:
    enabled: true

mysql:
    enabled: true
    mysqlRootPassword: PASSWORD
    mysqlAllowEmptyPassword: false
    initializationFiles:
        init.sql: |-
            CREATE DATABASE IF NOT EXISTS mlflow;
    configurationFilesPath: /etc/mysql/
    configurationFiles:
        my.cnf: |-
            [mysqld]
            explicit_defaults_for_timestamp = 1

minio:
    enabled: true
    accessKey: minio
    secretKey: minio123
    service:
        type: NodePort

airflow:
    enabled: true
    postgresql:
        enabled: false
    externalDatabase:
        type: mysql
        host: ai-workspace-mysql
        port: 3306
        passwordSecret: aiw-secret
        passwordSecretKey: dbpassword
    redis:
        enabled: false
