# Default values for AI Workspace
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
    secret:
        dbhost: ai-workspace-mysql
        dbuser: root
        dbpassword: PASSWORD
        aws_access_key_id: minio
        aws_secret_access_key: minio123
        mlflow_s3_endpoint_url: http://ai-workspace-minio:9000 
    dashboard:
        enabled: true
    jupyterhub:
        enabled: true
    mlflow:
        enabled: false
    phpmyadmin:
        enabled: false
    mysql:
        enabled: true
    minio:
        enabled: false
    airflow:
        enabled: false 
    theia:
        enabled: false
    tensorboard:
        enabled: false

jupyterhub: 
    proxy:
        secretToken: "bcd448e284d1a2acdb85a14844a1829a2d9703c3606362b0a72cd6d28441816c"
    hub:
        service:
            type: NodePort
        db:
            type: mysql
            url: mysql+pymysql://root:PASSWORD@ai-workspace-mysql:3306/jupyterhub

mysql: 
    mysqlRootPassword: PASSWORD
    mysqlAllowEmptyPassword: false
    initializationFiles:
        init.sql: |-
            CREATE DATABASE IF NOT EXISTS mlflow;
            CREATE DATABASE IF NOT EXISTS airflow;
            CREATE DATABASE IF NOT EXISTS jupyterhub;
    configurationFilesPath: /etc/mysql/
    configurationFiles:
        my.cnf: |-
            [mysqld]
            explicit_defaults_for_timestamp = 1

minio: 
    accessKey: minio
    secretKey: minio123
    service:
        type: NodePort

airflow: 
    postgresql:
        enabled: false
    externalDatabase:
        type: mysql
        host: ai-workspace-mysql
        port: 3306
        passwordSecret: aiw-secret
        passwordSecretKey: dbpassword
    redis:
        enabled: false
